---
title: "'Catch' bir 'Try' deyimi dışında yer alamaz"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 861057ff4d7c68a5917bddbb8d7361946f3f43f5
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 03/15/2019
ms.locfileid: "58041180"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' bir 'Try' deyimi dışında yer alamaz
`Catch` içinde görünmelidir bir `Try...Catch...Finally` deyim bloğu. Ya da gereksiz bir sahip `Catch` deyiminde, `Try` bloğu veya `Catch` deyimi, karşılık gelen sınırları dışında görünür `Try` blok.  
  
 **Hata Kimliği:** BC30380  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1.  Silme `Catch` gereksizdir veya içine yerleştirdiğiniz deyimi bir `Try...Catch...Finally` deyim bloğu.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
