---
title: "'Catch' bir 'Try' deyimi dışında yer alamaz"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: d1b910848ccc5b8f0228108a5cdef04e03d60891
ms.sourcegitcommit: 6b308cf6d627d78ee36dbbae8972a310ac7fd6c8
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 01/23/2019
ms.locfileid: "54517957"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' bir 'Try' deyimi dışında yer alamaz
`Catch` içinde görünmelidir bir `Try...Catch...Finally` deyim bloğu. Ya da gereksiz bir sahip `Catch` deyiminde, `Try` bloğu veya `Catch` deyimi, karşılık gelen sınırları dışında görünür `Try` blok.  
  
 **Hata Kimliği:** BC30380  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1.  Silme `Catch` gereksizdir veya içine yerleştirdiğiniz deyimi bir `Try...Catch...Finally` deyim bloğu.  
  
## <a name="see-also"></a>Ayrıca bkz.
- [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)

