---
title: "'Catch' bloğuna erişilemedi; <exception> yukarıda aynı Try' deyiminde işlendi"
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 3bbb76264ba28f7f74e1ec626adf2c09a50273d4
ms.sourcegitcommit: bef803e2025642df39f2f1e046767d89031e0304
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 02/15/2019
ms.locfileid: "56304329"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>'Catch' bloğuna erişilemedi; \<özel durum > yukarıda aynı Try' deyiminde işlendi
A `Catch` kod bloğunda, bir önceki işlendiğinden ulaşılamıyor `Try` blok.  
  
Varsayılan olarak, bu iletiyi bir uyarıdır. Uyarıları gizleme veya uyarıları hata olarak değerlendirmesini hakkında daha fazla bilgi için bkz. [Visual Basic'teki uyarıları yapılandırma](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **Hata Kimliği:** BC42031  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
-   Gereksiz bildirimi Kaldır.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Özel durumları yakalamak için try/catch bloğu kullanma](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Kullanıcı Tarafından Filtrelenmiş Özel Durum İşleyicilerini Kullanma](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
