---
ms.openlocfilehash: 94fad6fe910da6c528c5e13f529a6db274e07d5c
ms.sourcegitcommit: 0be8a279af6d8a43e03141e349d3efd5d35f8767
ms.translationtype: HT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/18/2019
ms.locfileid: "59235921"
---
### <a name="change-in-behavior-for-taskwaitall-methods-with-time-out-arguments"></a><span data-ttu-id="f7ce0-101">Zaman aşımı bağımsız değişkenleri Task.WaitAll yöntemleriyle davranışını değiştir</span><span class="sxs-lookup"><span data-stu-id="f7ce0-101">Change in behavior for Task.WaitAll methods with time-out arguments</span></span>

|   |   |
|---|---|
|<span data-ttu-id="f7ce0-102">Ayrıntılar</span><span class="sxs-lookup"><span data-stu-id="f7ce0-102">Details</span></span>|<span data-ttu-id="f7ce0-103"><xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType> davranışı Bu yöntemler tutarsız hatalı davranan .NET Framework 4 .NET Framework 4.5.In daha tutarlı olarak yapıldı.</span><span class="sxs-lookup"><span data-stu-id="f7ce0-103"><xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType> behavior was made more consistent in .NET Framework 4.5.In the .NET Framework 4, these methods behaved inconsistently.</span></span> <span data-ttu-id="f7ce0-104">Bir veya daha fazla görev tamamlandıysa veya yöntem çağrısından önce iptal edildi, zaman aşımı süresi dolduğunda, yöntem oluşturdu bir <xref:System.AggregateException?displayProperty=name> özel durum.</span><span class="sxs-lookup"><span data-stu-id="f7ce0-104">When the time-out expired, if one or more tasks were completed or canceled before the method call, the method threw an <xref:System.AggregateException?displayProperty=name> exception.</span></span> <span data-ttu-id="f7ce0-105">Hiçbir görev tamamlanmadıysa veya yöntem çağrısından önce iptal edildi, ancak bir veya daha fazla görev bu durumlara yöntem çağrısından sonra girilen zaman aşımı süresi dolduğunda, yöntem false döndürdü.</span><span class="sxs-lookup"><span data-stu-id="f7ce0-105">When the time-out expired, if no tasks were completed or canceled before the method call, but one or more tasks entered these states after the method call, the method returned false.</span></span><br/><br/><span data-ttu-id="f7ce0-106">.NET Framework 4.5, bu yöntem aşırı yüklemeleri artık herhangi bir görev zaman aşımı aralığı sona ve oluştururlar hala çalıştırıyorsanız, return false bir <xref:System.AggregateException?displayProperty=name> (bunu önce veya sonra yöntemi olup olmadığından bağımsız olarak bir giriş görev yalnızca iptal edildiyse özel durumu Çağrı) ve diğer hiçbir görev hala çalışıyor.</span><span class="sxs-lookup"><span data-stu-id="f7ce0-106">In the .NET Framework 4.5, these method overloads now return false if any tasks are still running when the time-out interval expired, and they throw an <xref:System.AggregateException?displayProperty=name> exception only if an input task was cancelled (regardless of whether it was before or after the method call) and no other tasks are still running.</span></span>|
|<span data-ttu-id="f7ce0-107">Öneri</span><span class="sxs-lookup"><span data-stu-id="f7ce0-107">Suggestion</span></span>|<span data-ttu-id="f7ce0-108">Varsa bir <xref:System.AggregateException?displayProperty=name> algılama öncesinde iptal edildi bir görev olarak yakalanan <xref:System.Threading.Tasks.Task.WaitAll%2A> çağrılan kodu aracılığıyla aynı algılama yerine yapmalısınız çağrı <xref:System.Threading.Tasks.Task.IsCanceled%2A> özelliği (örneğin:. Any(t =&gt; t.IsCanceled)) olduğundan tüm beklenen görev zaman aşımı önce tamamlanırsa .NET Framework 4.6 yalnızca bu durumda durum oluşturur.</span><span class="sxs-lookup"><span data-stu-id="f7ce0-108">If an <xref:System.AggregateException?displayProperty=name> was being caught as a means of detecting a task that was cancelled prior to the <xref:System.Threading.Tasks.Task.WaitAll%2A> call being invoked, that code should instead do the same detection via the  <xref:System.Threading.Tasks.Task.IsCanceled%2A> property (for example: .Any(t =&gt; t.IsCanceled)) since .NET Framework 4.6 will only throw in that case if all awaited tasks are completed prior to the timeout.</span></span>|
|<span data-ttu-id="f7ce0-109">Kapsam</span><span class="sxs-lookup"><span data-stu-id="f7ce0-109">Scope</span></span>|<span data-ttu-id="f7ce0-110">İkincil</span><span class="sxs-lookup"><span data-stu-id="f7ce0-110">Minor</span></span>|
|<span data-ttu-id="f7ce0-111">Sürüm</span><span class="sxs-lookup"><span data-stu-id="f7ce0-111">Version</span></span>|<span data-ttu-id="f7ce0-112">4,5</span><span class="sxs-lookup"><span data-stu-id="f7ce0-112">4.5</span></span>|
|<span data-ttu-id="f7ce0-113">Tür</span><span class="sxs-lookup"><span data-stu-id="f7ce0-113">Type</span></span>|<span data-ttu-id="f7ce0-114">Çalışma zamanı</span><span class="sxs-lookup"><span data-stu-id="f7ce0-114">Runtime</span></span>|
|<span data-ttu-id="f7ce0-115">Etkilenen API’ler</span><span class="sxs-lookup"><span data-stu-id="f7ce0-115">Affected APIs</span></span>|<ul><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32,System.Threading.CancellationToken)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.TimeSpan)?displayProperty=nameWithType></li></ul>|
